{% set version = "1.8.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-picante
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/picante_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/picante/picante_{{ version }}.tar.gz
  sha256: e04379a2ab588c51fce1848973dc3c6470b6326b334fb4020a544bf951fd26ac

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ape
    - r-nlme
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ape
    - r-nlme
    - r-vegan

test:
  commands:
    - $R -e "library('picante')"           # [not win]
    - "\"%R%\" -e \"library('picante')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=picante
  license: GPL-2
  summary: Functions for phylocom integration, community analyses, null-models, traits and evolution.
    Implements numerous ecophylogenetic approaches including measures of community phylogenetic
    and trait diversity, phylogenetic signal, estimation of trait values for unobserved
    taxa, null models for community and phylogeny randomizations, and utility functions
    for data input/output and phylogeny plotting. A full description of package functionality
    and methods are provided by Kembel et al. (2010) <doi:10.1093/bioinformatics/btq166>.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - nick-youngblut
    - conda-forge/r

# Package: picante
# Type: Package
# Title: Integrating Phylogenies and Ecology
# Version: 1.8
# Date: 2019-03-21
# Author: Steven W. Kembel <steve.kembel@gmail.com>, David D. Ackerly <dackerly@berkeley.edu>, Simon P. Blomberg <s.blomberg1@uq.edu.au>, Will K. Cornwell <cornwell@zoology.ubc.ca>, Peter D. Cowan <pdc@berkeley.edu>, Matthew R. Helmus <mrhelmus@wisc.edu>, Helene Morlon <morlon.helene@gmail.com>, Campbell O. Webb <cwebb@oeb.harvard.edu>
# Maintainer: Steven W. Kembel <steve.kembel@gmail.com>
# Depends: ape, vegan, nlme, methods
# Suggests: brglm, circular, corpcor, quantreg
# Description: Functions for phylocom integration, community analyses, null-models, traits and evolution. Implements numerous ecophylogenetic approaches including measures of community phylogenetic and trait diversity, phylogenetic signal, estimation of trait values for unobserved taxa, null models for community and phylogeny randomizations, and utility functions for data input/output and phylogeny plotting. A full description of package functionality and methods are provided by Kembel et al. (2010) <doi:10.1093/bioinformatics/btq166>.
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-03-21 14:48:42 UTC; steve
# Repository: CRAN
# Date/Publication: 2019-03-21 15:30:03 UTC
